### ISSUE TITLE
How to remove make_delegate?

### ISSUE THREAD

**Issue by stallion5632** [421p/Delegator#2]
I try change
```
    auto closure = make_delegate<string>([](string item) {
        cout << "Item added: " << item << endl;
    });

    collection.itemAdded += closure;
```
 to
 ```
  auto func = [](string item) {
        cout << "Item added: " << item << endl;
    };
  collection.itemAdded += func;
 ``` 
  because I can not write the **unsubscribe** function.
  
  inline void unsubscribe(std::shared_ptr<DelegateVoid> callable)
    {
        _listeners->remove(callable);
    }
    
    Do you have any way ?

**Comment by haswelldev** [comment]
I'm not sure that I understand the question.
Could you describe the problem in more detail?

probably this may help https://github.com/421p/Delegator/blob/master/tests/complex_test.cpp#L43

**Comment by haswelldev** [comment]
#inactivity
